# Generated by Django 3.1.3 on 2020-11-07 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patient_full_name',
            new_name='patient_first_name',
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_initial',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient_last_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
