# Generated by Django 3.1.3 on 2020-11-08 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0002_auto_20201107_2214'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='provider',
            options={'ordering': ('provider_full_name',)},
        ),
        migrations.AddField(
            model_name='provider',
            name='city',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='country',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='latitude',
            field=models.FloatField(default=19, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='provider',
            name='longitude',
            field=models.FloatField(default=-66, max_length=255),
            preserve_default=False,
        ),
    ]
