# Generated by Django 3.1.3 on 2020-11-11 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace', '0004_auto_20201110_2053'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='approved',
            field=models.BooleanField(default=True),
        ),
    ]
